$(document).ready(function () {
    //llenado de la entidad cabecera historia
    var cabecera = function(){
        this.IDE_CONTRATO = $("#ctl00_ContentPlaceHolder1_ddl_contrato").val()
    };
    //llenado de la entidad historia detalle
    var historiaLinDet = function () {
        this.COD_AFP = $("#ctl00_ContentPlaceHolder1_ddl_afp").val(),
        this.TIP_MONE = $("#ctl00_ContentPlaceHolder1_ddl_moneda").val(),
        this.COD_CUSP = $("#ctl00_ContentPlaceHolder1_txt_cod_cusp").val(),
        this.APE_MATE_PEN = $("#ctl00_ContentPlaceHolder1_txt_apellido").val(),
        this.PRI_NOMB_PEN = $("#ctl00_ContentPlaceHolder1_txt_nombre").val(),
        this.NUM_DOCU_PEN = $("#ctl00_ContentPlaceHolder1_txt_dni").val(),
        this.NUM_SOLI_PEN = $("#ctl00_ContentPlaceHolder1_txt_nro_solicitud").val()
    };
    //boton de consultar
    $("section").delegate("#ctl00_ContentPlaceHolder1_btn_consultar", "click", function (ev) {
        ev.preventDefault();
        //aca se adicionara algunos valores que no se encuentren en la tabla historia cabecera
        var filterParam = [$("#ctl00_ContentPlaceHolder1_ddl_tipo_archivo").val(),$("#ctl00_ContentPlaceHolder1_txt_fec_ini_o").val(),$("#ctl00_ContentPlaceHolder1_txt_fec_hasta_o").val()];
        console.log(filterParam);
        jatbleRequestOperacion(new cabecera(),new historiaLinDet(),filterParam, false, "5000");
    });
    function jatbleRequestOperacion(cabecera, historiaLinDet,filterParam, visibleColumn, sizetable) {
        $('#frmSeqConsulta').jtable({
            tableId: 'tblSeqConsulta',
            paging: true,
            sorting: true,
            selecting: false,
            pageSize: 13,
            defaultSorting: 'IdHistorialCargaArchivoLinCab ASC',
            actions: {
                listAction: '/WebPage/ModuloDIS/Consultas/frmSegConsulta.aspx/listHistoriaDetalle'
            },
            fields: {
                IdHistorialCargaArchivoLinDet: { title: 'IdHistorialCargaArchivoLinDet' },
                IdHistorialCargaArchivoLinCab: { title: 'IdHistorialCargaArchivoLinCab' },
                FechaInsert: { title: 'FechaInsert', type: 'date', displayFormat:'dd/mm/yy' },
                TipoLinea: { title: 'TipoLinea' },
                NumeroLinea: { title: 'NumeroLinea' },
                FEC_DEVE: { title: 'FEC_DEVE', type: 'date', displayFormat: 'dd/mm/yy' },
                FEC_FALL: { title: 'FEC_FALL', type: 'date', displayFormat: 'dd/mm/yy' },
                FEC_OCUR: { title: 'FEC_OCUR', type: 'date', displayFormat: 'dd/mm/yy' },
                FEC_PAGO_APO_ADI: { title: 'FEC_PAGO_APO_ADI', type: 'date', displayFormat: 'dd/mm/yy' },
                FEC_INV_DEF: { title: 'FEC_INV_DEF', type: 'date', displayFormat: 'dd/mm/yy' },
                CAP_GAST_SEP: { title: 'CAP_GAST_SEP' },
                PARE: { title: 'PARE' },
                SAL_CIC_SOL: { title: 'SAL_CIC_SOL' },
                TIP_REGI: { title: 'TIP_REGI' },
                TIP_SOLI: { title: 'TIP_SOLI' },
                NUM_BENE: { title: 'NUM_BENE' },
                NUM_MESE_DEV: { title: 'NUM_MESE_DEV' },
                POR_BENE: { title: 'POR_BENE' },
                TIP_IDEN_SOL: { title: 'TIP_IDEN_SOL' },
                TIP_PENS: { title: 'TIP_PENS' },
                TIP_DOCU_IDE_PEN: { title: 'TIP_DOCU_IDE_PEN' },
                TIP_MOVI: { title: 'TIP_MOVI' },
                COD_CSV_01: { title: 'COD_CSV_01' },
                COD_CSV_02: { title: 'COD_CSV_02' },
                COD_CSV_03: { title: 'COD_CSV_03' },
                COD_CSV_04: { title: 'COD_CSV_04' },
                COD_CSV_05: { title: 'COD_CSV_05' },
                COD_CSV_06: { title: 'COD_CSV_06' },
                COD_CSV_07: { title: 'COD_CSV_07' },
                COD_CSV_08: { title: 'COD_CSV_08' },
                COD_AFP: { title: 'COD_AFP' },
                COD_IDE_CSV: { title: 'COD_IDE_CSV' },
                FRA_MESE_DEV: { title: 'FRA_MESE_DEV' },
                IND_PENS_PRE: { title: 'IND_PENS_PRE' },
                MTO_PPRE_ORI: { title: 'MTO_PPRE_ORI' },
                TIP_CAMB_VTA: { title: 'TIP_CAMB_VTA' },
                EXC_PENS_SOL: { title: 'EXC_PENS_SOL' },
                EXC_PENS_NM: { title: 'EXC_PENS_NM' },
                MES_DEVE: { title: 'MES_DEVE' },
                CAP_REQU_PEN: { title: 'CAP_REQU_PEN' },
                CRU_FAMI: { title: 'CRU_FAMI' },
                FEC_NACI: { title: 'FEC_NACI', type: 'date', displayFormat: 'dd/mm/yy' },
                FEC_NACI_PEN: { title: 'FEC_NACI_PEN', type: 'date', displayFormat: 'dd/mm/yy' },
                FEC_PAGO: { title: 'FEC_PAGO', type: 'date', displayFormat: 'dd/mm/yy' },
                FEC_PAGO_TEX: { title: 'FEC_PAGO_TEX', type: 'date', displayFormat: 'dd/mm/yy' },
                FEC_SECI: { title: 'FEC_SECI', type: 'date', displayFormat: 'dd/mm/yy' },
                FEC_SINI_OCU: { title: 'FEC_SINI_OCU', type: 'date', displayFormat: 'dd/mm/yy' },
                FEC_DEVE_ACT: { title: 'FEC_DEVE_ACT', type: 'date', displayFormat: 'dd/mm/yy' },
                FEC_DEVE_INI: { title: 'FEC_DEVE_INI', type: 'date', displayFormat: 'dd/mm/yy' },
                FEC_FIN_SUB: { title: 'FEC_FIN_SUB', type: 'date', displayFormat: 'dd/mm/yy' },
                RAM_PROM_SOL: { title: 'RAM_PROM_SOL' },
                TAS_INTE: { title: 'TAS_INTE' },
                VACIO_10: { title: 'VACIO_10' },
                DES_PENS_MONE: { title: 'DES_PENS_MONE' },
                MTO_APOR_ADI: { title: 'MTO_APOR_ADI' },
                MTO_APOR_ADI_SOL: { title: 'MTO_APOR_ADI_SOL' },
                MTO_APOR_COM: { title: 'MTO_APOR_COM' },
                MTO_PENS_PAG: { title: 'MTO_PENS_PAG' },
                MTO_PPRE_MN: { title: 'MTO_PPRE_MN' },
                MTO_APOR_OBL: { title: 'MTO_APOR_OBL' },
                MTO_MONE_APO_COM1: { title: 'MTO_MONE_APO_COM1' },
                MTO_MONE_APO_COM2: { title: 'MTO_MONE_APO_COM2' },
                MTO_MONE_APO_COM3: { title: 'MTO_MONE_APO_COM3' },
                MTO_MONE_APO_COM4: { title: 'MTO_MONE_APO_COM4' },
                MTO_MONE_APO_COM5: { title: 'MTO_MONE_APO_COM5' },
                MTO_MONE_APO_COM6: { title: 'MTO_MONE_APO_COM6' },
                MTO_MONE_APO_COM7: { title: 'MTO_MONE_APO_COM7' },
                MTO_MONE_APO_COM8: { title: 'MTO_MONE_APO_COM8' },
                MTO_MONE_APO_OBL1: { title: 'MTO_MONE_APO_OBL1' },
                MTO_MONE_APO_OBL2: { title: 'MTO_MONE_APO_OBL2' },
                MTO_MONE_APO_OBL3: { title: 'MTO_MONE_APO_OBL3' },
                MTO_MONE_APO_OBL4: { title: 'MTO_MONE_APO_OBL4' },
                MTO_MONE_APO_OBL5: { title: 'MTO_MONE_APO_OBL5' },
                MTO_MONE_APO_OBL6: { title: 'MTO_MONE_APO_OBL6' },
                MTO_MONE_APO_OBL7: { title: 'MTO_MONE_APO_OBL7' },
                MTO_MONE_APO_OBL8: { title: 'MTO_MONE_APO_OBL8' },
                MTO_PAGO_REE_SOL: { title: 'MTO_PAGO_REE_SOL' },
                MTO_PRIM_PAG_PENS_AFP1: { title: 'MTO_PRIM_PAG_PENS_AFP1' },
                MTO_PRIM_PAG_PENS_AFP2: { title: 'MTO_PRIM_PAG_PENS_AFP2' },
                MTO_PRIM_PAG_PENS_AFP3: { title: 'MTO_PRIM_PAG_PENS_AFP3' },
                MTO_PRIM_PAG_PENS_AFP4: { title: 'MTO_PRIM_PAG_PENS_AFP4' },
                MTO_PRIM_PAG_PENS_AFP5: { title: 'MTO_PRIM_PAG_PENS_AFP5' },
                MTO_PRIM_PAG_PENS_AFP6: { title: 'MTO_PRIM_PAG_PENS_AFP6' },
                MTO_PRIM_PAG_PENS_AFP7: { title: 'MTO_PRIM_PAG_PENS_AFP7' },
                MTO_PRIM_PAG_PENS_AFP8: { title: 'MTO_PRIM_PAG_PENS_AFP8' },
                MTO_DSCT_PENS_PAG_AFP1: { title: 'MTO_DSCT_PENS_PAG_AFP1' },
                MTO_DSCT_PENS_PAG_AFP2: { title: 'MTO_DSCT_PENS_PAG_AFP2' },
                MTO_DSCT_PENS_PAG_AFP3: { title: 'MTO_DSCT_PENS_PAG_AFP3' },
                MTO_DSCT_PENS_PAG_AFP4: { title: 'MTO_DSCT_PENS_PAG_AFP4' },
                MTO_DSCT_PENS_PAG_AFP5: { title: 'MTO_DSCT_PENS_PAG_AFP5' },
                MTO_DSCT_PENS_PAG_AFP6: { title: 'MTO_DSCT_PENS_PAG_AFP6' },
                MTO_DSCT_PENS_PAG_AFP7: { title: 'MTO_DSCT_PENS_PAG_AFP7' },
                MTO_DSCT_PENS_PAG_AFP8: { title: 'MTO_DSCT_PENS_PAG_AFP8' },
                MTO_SOLE_APO_ADI_AFP1: { title: 'MTO_SOLE_APO_ADI_AFP1' },
                MTO_SOLE_APO_ADI_AFP2: { title: 'MTO_SOLE_APO_ADI_AFP2' },
                MTO_SOLE_APO_ADI_AFP3: { title: 'MTO_SOLE_APO_ADI_AFP3' },
                MTO_SOLE_APO_ADI_AFP4: { title: 'MTO_SOLE_APO_ADI_AFP4' },
                MTO_SOLE_APO_ADI_AFP5: { title: 'MTO_SOLE_APO_ADI_AFP5' },
                MTO_SOLE_APO_ADI_AFP6: { title: 'MTO_SOLE_APO_ADI_AFP6' },
                MTO_SOLE_APO_ADI_AFP7: { title: 'MTO_SOLE_APO_ADI_AFP7' },
                MTO_SOLE_APO_ADI_AFP8: { title: 'MTO_SOLE_APO_ADI_AFP8' },
                MTO_SOLE_REE_PAG_AFP1: { title: 'MTO_SOLE_REE_PAG_AFP1' },
                MTO_SOLE_REE_PAG_AFP2: { title: 'MTO_SOLE_REE_PAG_AFP2' },
                MTO_SOLE_REE_PAG_AFP3: { title: 'MTO_SOLE_REE_PAG_AFP3' },
                MTO_SOLE_REE_PAG_AFP4: { title: 'MTO_SOLE_REE_PAG_AFP4' },
                MTO_SOLE_REE_PAG_AFP5: { title: 'MTO_SOLE_REE_PAG_AFP5' },
                MTO_SOLE_REE_PAG_AFP6: { title: 'MTO_SOLE_REE_PAG_AFP6' },
                MTO_SOLE_REE_PAG_AFP7: { title: 'MTO_SOLE_REE_PAG_AFP7' },
                MTO_SOLE_REE_PAG_AFP8: { title: 'MTO_SOLE_REE_PAG_AFP8' },
                NRO_CSV: { title: 'NRO_CSV' },
                NUM_DOCU_SOL: { title: 'NUM_DOCU_SOL' },
                NUM_SINI: { title: 'NUM_SINI' },
                NUM_SOLI: { title: 'NUM_SOLI' },
                NUM_SOLI_PEN: { title: 'NÚM_SOLI_PEN' },
                NUM_DOCU_PEN: { title: 'NÚM_DOCU_PEN' },
                PEN_PAGA_MON: { title: 'PEN_PAGA_MON' },
                PEN_BASE_MON: { title: 'PEN_BASE_MON' },
                REM_PROM_ACT: { title: 'REM_PROM_ACT' },
                NUM_APOR_ACT: { title: 'NUM_APOR_ACT' },
                SAL_CIC_MN: { title: 'SAL_CIC_MN' },
                TIP_CAMB_COM: { title: 'TIP_CAMB_COM' },
                TIP_MONE: { title: 'TIP_MONE' },
                TOT_CAPI_REQ_MN: { title: 'TOT_CAPI_REQ_MN' },
                TOT_CAPI_REQ_ORI: { title: 'TOT_CAPI_REQ_ORI' },
                COD_CUSP: { title: 'COD_CUSP' },
                COD_BENE_MN: { title: 'COD_BENE_MN' },
                APE_MATE_PEN: { title: 'APE_MATE_PEN' },
                APE_MATE_SOLI: { title: 'APE_MATE_SOLI' },
                APE_PATE_PEN: { title: 'APE_PATE_PEN' },
                APE_PATE_SOL: { title: 'APE_PATE_SOL' },
                PRI_NOMB_PEN: { title: 'PRI_NOMB_PEN' },
                PRI_NOMB_SOL: { title: 'PRI_NOMB_SOL' },
                SEG_NOMB_PEN: { title: 'SEG_NOMB_PEN' },
                SEG_NOMB_SOL: { title: 'SEG_NOMB_SOL' },
                SUC_INTE: { title: 'SUC_INTE' },
                CumpleValidacion: { title: 'CumpleValidacion' }
            }
        });
        $('#frmSeqConsulta.jtable-main-container').css({ "width": sizetable });
        $('#frmSeqConsulta').jtable('load', { 'cabecera': cabecera, 'historiaLinDet': historiaLinDet, 'filterParam': filterParam });
    }
});