
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class CIERRE_PROCESO
{

    public int ID_CIERRE { get; set; }

    public string NRO_CONTRATO { get; set; }

    public string TIPO_INFO { get; set; }

    public Nullable<System.DateTime> FEC_CIE { get; set; }

    public Nullable<int> ANIO_CIERRE { get; set; }

    public Nullable<int> MES_CIERRE { get; set; }

    public int NRO_REGISTRO { get; set; }

    public string TIPO_CIERRE { get; set; }

    public Nullable<decimal> TOTAL_MONTO { get; set; }

    public string ESTADO { get; set; }

    public System.DateTime FEC_REG { get; set; }

    public string USU_REG { get; set; }

}

}
