//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_DETALLE
    {
        public Nullable<int> ID_EMPRESA { get; set; }
        public int IDE_CONTRATO_DET { get; set; }
        public string NRO_CONTRATO { get; set; }
        public string IDE_REASEGURADOR { get; set; }
        public string COD_REASEGURADOR { get; set; }
        public string CAL_CREDITICIA { get; set; }
        public string COD_EMPRESA_CALIFICA { get; set; }
        public string MOD_CONTRATO { get; set; }
        public Nullable<decimal> PRC_RETENCION { get; set; }
        public Nullable<decimal> PRC_CESION { get; set; }
        public decimal PRC_PARTICIPACION_REA { get; set; }
        public string NOMBRE_REA { get; set; }
        public Nullable<int> NRO_REGISTRO_REA { get; set; }
        public string ESTADO { get; set; }
        public string USU_REG { get; set; }
        public System.DateTime FEC_REG { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USU_MOD { get; set; }
    }
}
