//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_SYS
    {
        public Nullable<int> ID_EMPRESA { get; set; }
        public int IDE_CONTRATO { get; set; }
        public string NRO_CONTRATO { get; set; }
        public string CLA_CONTRATO { get; set; }
        public System.DateTime FEC_INI_VIG { get; set; }
        public System.DateTime FEC_FIN_VIG { get; set; }
        public string DES_CONTRATO { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FEC_REG { get; set; }
        public string USU_REG { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USU_MOD { get; set; }
    }
}
