
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class CONTRATO_SIS_DET
{

    public int IDE_CONTRATO_DET { get; set; }

    public Nullable<int> IDE_CONTRATO { get; set; }

    public Nullable<int> COD_CSV { get; set; }

    public Nullable<decimal> PRC_PARTICIACION { get; set; }

    public Nullable<int> NRO_ORDEN { get; set; }

    public string ESTADO { get; set; }

    public string USU_REG { get; set; }

    public System.DateTime FEC_REG { get; set; }

    public Nullable<System.DateTime> FEC_MOD { get; set; }

    public string USU_MOD { get; set; }



    public virtual CONTRATO_SYS CONTRATO_SYS { get; set; }

}

}
