//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATO_M
    {
        public Nullable<int> IDE_EMPRESA { get; set; }
        public int IDE_DATA_M { get; set; }
        public string TIPO_INFO { get; set; }
        public string NRO_CONTRATO { get; set; }
        public Nullable<int> ANIO_VIGENTE { get; set; }
        public Nullable<int> MES_VIGENTE { get; set; }
        public Nullable<int> MES_CONTABLE { get; set; }
        public string COD_RAMO { get; set; }
        public string COD_PRODUCTO { get; set; }
        public Nullable<decimal> MTO_ABONADO { get; set; }
        public Nullable<decimal> MTO_PRIMA_EST { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USU_REG { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USU_MOD { get; set; }
    }
}
