
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class Evento
{

    public string CodiEven { get; set; }

    public string TipoEven { get; set; }

    public string DescEven { get; set; }

    public string AbreEven { get; set; }

    public string EstEven { get; set; }

}

}
