//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXACTUS_CABECERA
    {
        public string NRO_CONTRATO { get; set; }
        public string TIPO_INFO { get; set; }
        public int ANIO_VIGENTE { get; set; }
        public int MES_VIGENTE { get; set; }
        public string ASIENTO { get; set; }
        public string PAQUETE { get; set; }
        public string TIPO_ASIENTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string CONTABILIDAD { get; set; }
        public string NOTAS { get; set; }
        public int ESTADO { get; set; }
        public string ESTADO_TRANSFERENCIA { get; set; }
        public string PERMITIR_DESCUADRADO { get; set; }
        public string CONSERVAR_NUMERACION { get; set; }
        public string ACTUALIZAR_CONSECUTIVO { get; set; }
        public Nullable<System.DateTime> FECHA_AUDITORIA { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_REGISTRO { get; set; }
    }
}
