//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENERAL
    {
        public int IDE_IMPRESA { get; set; }
        public string DESCRIPCION { get; set; }
        public string RUC_EMPRESA { get; set; }
        public int ANIO_VIGENTE { get; set; }
        public int MES_VEGENTE { get; set; }
        public string RUTA_ARCHIVO { get; set; }
        public Nullable<int> NRO_DECIMAL { get; set; }
        public Nullable<decimal> TCA_MES { get; set; }
        public Nullable<decimal> TCA_ANIO { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FEC_REG { get; set; }
        public string USU_REG { get; set; }
    }
}
