//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaCamara.DIS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogOperacion
    {
        public long CodiLogOper { get; set; }
        public Nullable<System.DateTime> FechEven { get; set; }
        public string TipoOper { get; set; }
        public string CodiOper { get; set; }
        public string CodiEven { get; set; }
        public Nullable<long> CodiUsu { get; set; }
        public string CodiCnx { get; set; }
    }
}
