
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VidaCamara.DIS.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class USUARIO
{

    public int IDE_USUARIO { get; set; }

    public string USUARIO1 { get; set; }

    public string CONTRASENA { get; set; }

    public string ACCESO_PAGINA { get; set; }

    public string NOMBRES { get; set; }

    public string CARGO { get; set; }

    public string EMAIL { get; set; }

    public string TIPO_USUARIO { get; set; }

    public string ESTADO { get; set; }

    public System.DateTime FEC_REG { get; set; }

    public string USU_REG { get; set; }

    public Nullable<System.DateTime> FEC_MOD { get; set; }

    public string USU_MOD { get; set; }

}

}
